name: "Task"
description: "작업 이슈 템플릿 🛠️"
title: "[Task] "
body:
  - type: dropdown
    attributes:
      label: 우선순위
      description: "작업 우선순위를 선택해주세요"
      options:
        - "🔴 Critical"
        - "🟠 High"
        - "🟢 Normal"
        - "🔵 Low"
      value: "🟢 Normal"

  - type: textarea
    attributes:
      label: 작업 목표
      description: "구현해야 할 내용을 명확히 작성해주세요"
      placeholder: |
        ### 목표
        ex) 사용자 로그인 기능 구현
        
        ### 범위
        ex) 
        - 정규식으로 이메일 검증
        - 재전송 상태관리 처리
        - JWT 토큰 관리
    validations:
      required: true